// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: proto/address.proto

package address

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryCode string `protobuf:"bytes,1,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	Locality    string `protobuf:"bytes,2,opt,name=locality,proto3" json:"locality,omitempty"`
	Street      string `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber string `protobuf:"bytes,4,opt,name=houseNumber,proto3" json:"houseNumber,omitempty"`
	PostalCode  string `protobuf:"bytes,5,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_address_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Address) GetLocality() string {
	if x != nil {
		return x.Locality
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type Fias struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fias string `protobuf:"bytes,1,opt,name=fias,proto3" json:"fias,omitempty"`
}

func (x *Fias) Reset() {
	*x = Fias{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_address_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fias) ProtoMessage() {}

func (x *Fias) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fias.ProtoReflect.Descriptor instead.
func (*Fias) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{1}
}

func (x *Fias) GetFias() string {
	if x != nil {
		return x.Fias
	}
	return ""
}

type GeonameId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeonameId string `protobuf:"bytes,1,opt,name=geonameId,proto3" json:"geonameId,omitempty"`
}

func (x *GeonameId) Reset() {
	*x = GeonameId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_address_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeonameId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeonameId) ProtoMessage() {}

func (x *GeonameId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeonameId.ProtoReflect.Descriptor instead.
func (*GeonameId) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{2}
}

func (x *GeonameId) GetGeonameId() string {
	if x != nil {
		return x.GeonameId
	}
	return ""
}

var File_proto_address_proto protoreflect.FileDescriptor

var file_proto_address_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xa1,
	0x01, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x1a, 0x0a, 0x04, 0x46, 0x69, 0x61, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69,
	0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x61, 0x73, 0x22, 0x29,
	0x0a, 0x09, 0x47, 0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67,
	0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x67, 0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x32, 0x6f, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x46, 0x69, 0x61, 0x73, 0x12,
	0x10, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x1a, 0x0d, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x46, 0x69, 0x61, 0x73,
	0x22, 0x00, 0x12, 0x36, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x47, 0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x12, 0x10, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x1a, 0x12, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x47,
	0x65, 0x6f, 0x6e, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x6f,
	0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_address_proto_rawDescOnce sync.Once
	file_proto_address_proto_rawDescData = file_proto_address_proto_rawDesc
)

func file_proto_address_proto_rawDescGZIP() []byte {
	file_proto_address_proto_rawDescOnce.Do(func() {
		file_proto_address_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_address_proto_rawDescData)
	})
	return file_proto_address_proto_rawDescData
}

var file_proto_address_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_address_proto_goTypes = []interface{}{
	(*Address)(nil),   // 0: address.Address
	(*Fias)(nil),      // 1: address.Fias
	(*GeonameId)(nil), // 2: address.GeonameId
}
var file_proto_address_proto_depIdxs = []int32{
	0, // 0: address.address.getFias:input_type -> address.Address
	0, // 1: address.address.getGeonameId:input_type -> address.Address
	1, // 2: address.address.getFias:output_type -> address.Fias
	2, // 3: address.address.getGeonameId:output_type -> address.GeonameId
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_address_proto_init() }
func file_proto_address_proto_init() {
	if File_proto_address_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_address_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_address_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fias); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_address_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeonameId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_address_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_address_proto_goTypes,
		DependencyIndexes: file_proto_address_proto_depIdxs,
		MessageInfos:      file_proto_address_proto_msgTypes,
	}.Build()
	File_proto_address_proto = out.File
	file_proto_address_proto_rawDesc = nil
	file_proto_address_proto_goTypes = nil
	file_proto_address_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddressClient is the client API for Address service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressClient interface {
	GetFias(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Fias, error)
	GetGeonameId(ctx context.Context, in *Address, opts ...grpc.CallOption) (*GeonameId, error)
}

type addressClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressClient(cc grpc.ClientConnInterface) AddressClient {
	return &addressClient{cc}
}

func (c *addressClient) GetFias(ctx context.Context, in *Address, opts ...grpc.CallOption) (*Fias, error) {
	out := new(Fias)
	err := c.cc.Invoke(ctx, "/address.address/getFias", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressClient) GetGeonameId(ctx context.Context, in *Address, opts ...grpc.CallOption) (*GeonameId, error) {
	out := new(GeonameId)
	err := c.cc.Invoke(ctx, "/address.address/getGeonameId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressServer is the server API for Address service.
type AddressServer interface {
	GetFias(context.Context, *Address) (*Fias, error)
	GetGeonameId(context.Context, *Address) (*GeonameId, error)
}

// UnimplementedAddressServer can be embedded to have forward compatible implementations.
type UnimplementedAddressServer struct {
}

func (*UnimplementedAddressServer) GetFias(context.Context, *Address) (*Fias, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFias not implemented")
}
func (*UnimplementedAddressServer) GetGeonameId(context.Context, *Address) (*GeonameId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeonameId not implemented")
}

func RegisterAddressServer(s *grpc.Server, srv AddressServer) {
	s.RegisterService(&_Address_serviceDesc, srv)
}

func _Address_GetFias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServer).GetFias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address.address/GetFias",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServer).GetFias(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

func _Address_GetGeonameId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Address)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServer).GetGeonameId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address.address/GetGeonameId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServer).GetGeonameId(ctx, req.(*Address))
	}
	return interceptor(ctx, in, info, handler)
}

var _Address_serviceDesc = grpc.ServiceDesc{
	ServiceName: "address.address",
	HandlerType: (*AddressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getFias",
			Handler:    _Address_GetFias_Handler,
		},
		{
			MethodName: "getGeonameId",
			Handler:    _Address_GetGeonameId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/address.proto",
}
